[package]
name = "round_mult"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { version = "0.2.15", default-features = false }

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "bench"
harness = false
